### ISSUE TITLE
Weekly Scrum - [2024/11/25 ~ 2024/12/01]

### ISSUE THREAD

**Issue by ruiunknownrui** [Ruangfafa/GraduateAdmissionsManagementSystem#72]

**Comment by ruiunknownrui** [comment]
What I did this week:

- Store actual pdf files in the database and allow admin and prof to preview them #71  

What I will do next week:

- Allow admin and prof to view student's interested profs and research field

Rebecca Li
#101150053

**Comment by p82222** [comment]
What I did this week:

implement method to apply deadlines for applications 
#70 

What I will do next week:
Review codes with teammates and be ready to present for milestone 3

Chia-Yu Liu
#100698737

**Comment by Ruangfafa** [comment]
I did nothing = =

**Comment by ZeidAlwash** [comment]
I did the CSS for the remaining pages in the front end
