### ISSUE TITLE
allow admin and prof to view application detail

### ISSUE THREAD

**Issue by ruiunknownrui** [Ruangfafa/GraduateAdmissionsManagementSystem#73]
- [x] Admin can view student interested prof and research field
- [x] profs can view student interested prof and research field.

**Comment by mnmnk43434** [comment]
Hello, we tried to solve the issue.

This is what we did:

Modified the AdminEventController to include methods for fetching and displaying student interests (desired professors and research fields) for both admins and professors.

You can review changes in this commit: https://github.com/mnmnk43434/Ruangfafa-GraduateAdmissionsManagementSystem-73/commit/35a7acd51d937627ff0c410ed623003f1f740972.


> [!CAUTION]
> Disclaimer: The concept of solution was created by AI and you should never copy paste this code before you check the correctness of generated code. Solution might not be complete, you should use this code as an inspiration only.

---

If you no longer want Latta AI to attempt solving issues on your repository, you can block this account.
